#!/bin/sh
set -e

dlUrl='https://raw.githubusercontent.com/Zankoku-Okuno/technicolor/master/technicolor'
installPath="$HOME/bin/technicolor"

echo "[FILE] $installPath"
wget "$dlUrl" -O "$installPath"
chmod +x "$installPath"
