#!/bin/sh
set -e

dlUrl='https://downloads.haskell.org/~ghcup/x86_64-linux-ghcup'
installPath="$HOME/.ghcup/bin/ghcup"

echo "[FILE] $installPath"
mkdir -p "$(basename "$installPath")"
wget "$dlUrl" -O "$installPath"
chmod +x "$installPath"
