#!/bin/sh
set -e

dlUrl='https://raw.githubusercontent.com/edemko/skel/master/skel.sh'
installPath="$HOME/bin/skel"

echo "[FILE] $installPath"
wget "$dlUrl" -O "$installPath"
chmod +x "$installPath"
