#!/bin/sh
set -e

dlUrl='https://raw.githubusercontent.com/edemko/gitstat/master/gitstat.sh'
installPath="$HOME/bin/gitstat"

echo "[FILE] $installPath"
wget "$dlUrl" -O "$installPath"
chmod +x "$installPath"
